In [3]:
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.ui import Console
from autogen_ext.models.openai import OpenAIChatCompletionClient

In [5]:
from dotenv import load_dotenv
import os

load_dotenv()

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

In [7]:
model_client = OpenAIChatCompletionClient(model="gpt-4o"
)

agent_1 = AssistantAgent(name='my_assistant',model_client=model_client)

In [8]:
response = await agent_1.run(task="How is the weather in East Brunswick today?")
print(response)

messages=[TextMessage(id='c1a061fe-2b90-4b88-ba82-275a8a058ec9', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 4, 27, 305583, tzinfo=datetime.timezone.utc), content='How is the weather in East Brunswick today?', type='TextMessage'), TextMessage(id='71f5642c-b75b-4552-a79c-3283aa6146c6', source='my_assistant', models_usage=RequestUsage(prompt_tokens=45, completion_tokens=32), metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 4, 33, 172193, tzinfo=datetime.timezone.utc), content="I can't access real-time data, including weather information. However, you can check the current weather for East Brunswick using a reliable weather service or app. TERMINATE", type='TextMessage')] stop_reason=None


messages=[TextMessage(id='c1a061fe-2b90-4b88-ba82-275a8a058ec9', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 4, 27, 305583, tzinfo=datetime.timezone.utc), content='How is the weather in East Brunswick today?', type='TextMessage'), TextMessage(id='71f5642c-b75b-4552-a79c-3283aa6146c6', source='my_assistant', models_usage=RequestUsage(prompt_tokens=45, completion_tokens=32), metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 4, 33, 172193, tzinfo=datetime.timezone.utc), content="I can't access real-time data, including weather information. However, you can check the current weather for East Brunswick using a reliable weather service or app. TERMINATE", type='TextMessage')] stop_reason=None

In [9]:
response = await agent_1.run(task="Do you remember my last question?")
print(response)

messages=[TextMessage(id='3f2b57c6-37b0-40ed-8412-d889de56f6ef', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 6, 12, 916653, tzinfo=datetime.timezone.utc), content='Do you remember my last question?', type='TextMessage'), TextMessage(id='981149ab-cd7f-4833-9c6e-eff3a5840763', source='my_assistant', models_usage=RequestUsage(prompt_tokens=93, completion_tokens=14), metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 6, 13, 917776, tzinfo=datetime.timezone.utc), content='Yes, you asked about the weather in East Brunswick today. TERMINATE', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='3f2b57c6-37b0-40ed-8412-d889de56f6ef', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 6, 12, 916653, tzinfo=datetime.timezone.utc), content='Do you remember my last question?', type='TextMessage'), TextMessage(id='981149ab-cd7f-4833-9c6e-eff3a5840763', source='my_assistant', models_usage=RequestUsage(prompt_tokens=93, completion_tokens=14), metadata={}, created_at=datetime.datetime(2025, 7, 7, 19, 6, 13, 917776, tzinfo=datetime.timezone.utc), content='Yes, you asked about the weather in East Brunswick today. TERMINATE', type='TextMessage')] stop_reason=None

In [1]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from dotenv import load_dotenv
import os

In [3]:
load_dotenv()
os.environ["OPENROUTER_API_KEY"] = os.getenv("OPENROUTER_API_KEY")

In [8]:
model_client = OpenAIChatCompletionClient(model="deepseek/deepseek-chat-v3-0324:free",
                                          base_url="https://openrouter.ai/api/v1",
                                          api_key=os.getenv("OPENROUTER_API_KEY"),
                                          model_info={
        "family":'deepseek',
        "vision" :True,
        "function_calling":True,
        "json_output": False,
        "structured_output": False
    }
)

In [9]:
my_assistant = AssistantAgent(name="my_assistant", model_client=model_client)

In [10]:
 result = await my_assistant.run(task="Which football club is based out of East Yorkshire in England")

In [14]:
result

TaskResult(messages=[TextMessage(id='aca731c5-13aa-4c97-810d-35a58c1097b6', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 10, 23, 24, 55, 84350, tzinfo=datetime.timezone.utc), content='Which football club is based out of East Yorkshire in England', type='TextMessage'), TextMessage(id='5d562536-73ec-4b3a-b6be-bbc8f65f10b9', source='my_assistant', models_usage=RequestUsage(prompt_tokens=41, completion_tokens=38), metadata={}, created_at=datetime.datetime(2025, 7, 10, 23, 25, 0, 386626, tzinfo=datetime.timezone.utc), content='The football club based out of East Yorkshire, England, is Hull City AFC (Association Football Club). They play their home matches at the MKM Stadium in Hull. \n\nTERMINATE', type='TextMessage')], stop_reason=None)

TaskResult(messages=[TextMessage(id='aca731c5-13aa-4c97-810d-35a58c1097b6', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 10, 23, 24, 55, 84350, tzinfo=datetime.timezone.utc), content='Which football club is based out of East Yorkshire in England', type='TextMessage'), TextMessage(id='5d562536-73ec-4b3a-b6be-bbc8f65f10b9', source='my_assistant', models_usage=RequestUsage(prompt_tokens=41, completion_tokens=38), metadata={}, created_at=datetime.datetime(2025, 7, 10, 23, 25, 0, 386626, tzinfo=datetime.timezone.utc), content='The football club based out of East Yorkshire, England, is Hull City AFC (Association Football Club). They play their home matches at the MKM Stadium in Hull. \n\nTERMINATE', type='TextMessage')], stop_reason=None)